# Generated by Django 3.1.6 on 2021-02-11 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='deliveredAt',
            new_name='delivered_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='isDelivered',
            new_name='is_delivered',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='isPaid',
            new_name='is_paid',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paidAt',
            new_name='paid_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paymentMethod',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shippingPrice',
            new_name='shipping_price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='taxPrice',
            new_name='tax_price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='totalPrice',
            new_name='total_price',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postalCode',
            new_name='pin_code',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shippingPrice',
            new_name='shipping_price',
        ),
    ]
