# Generated by Django 3.1.6 on 2021-02-15 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
    ]
